author:
  name: Frederik Blichert Klovborg
  email: klovborg@gmail.com

sass:
  style: compressed
  sass_dir: assets/_scss

host: 0.0.0.0

title: Frederik Blichert Klovborg
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio for Frederik Blichert Klovborg. User experience,
  interaction and product designer. Showcase of work and
  process to boast about how awesome he is.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: klovborg
github_username:  frebliklo

# Build settings
markdown: kramdown
